### Crear administrador
POST http://localhost:3000/admin/signup
Content-Type: application/json

{
    "email": "danielayizet@gmail.com",
    "password": "123456",
    "name": "Daniela",
    "lastname": "Zapata Barahona",
    "prefix": "57",
    "cellphone": "3192860986",
    "birthdate" : "2003-10-03"
}